#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

if [[ -d "/opt/nvm" && -f "/usr/local/hestia/data/templates/web/nginx/NodeApp.sh" ]]
then
    echo "NodeApp appears to already be installed"
    exit
fi

############################################ 
# Install NodeJS, NVM, PM2, and grunt
############################################

# First install the latest NodeJS LTS version
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
apt-get install -y nodejs

# Install pm2 globally
npm install -g pm2

# Install node version manager, globally
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
mv ~/.nvm /opt/nvm
chmod -R 755 /opt/nvm
export NVM_DIR="/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/nvm:$PATH"

# Install last three NodeJS LTS versions
nvm install 14.21.1
nvm install 16.18.1
nvm install 18.12.1
nvm alias default 18.12.1

# Install grunt globally
npm install -g grunt-cli

############################################
# Install templates
############################################

rsync -r ./nginx/ /usr/local/hestia/data/templates/web/nginx/

############################################
# Update global bash.bashrc
############################################

if ! grep -Fxq "# begin hestiacp-nodeapp" "/etc/bash.bashrc";then

cat <<EOT >> /etc/bash.bashrc
# begin hestiacp-nodeapp
export NVM_DIR="/opt/nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/nvm:\$PATH"
# end hestiacp-nodeapp
EOT

fi
