#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

if [[ -d "/opt/nvm" && -f "/usr/local/hestia/data/templates/web/nginx/NodeApp.stpl" ]]
then
    echo "NodeApp appears to already be installed"
    exit
fi

############################################ 
# Install NVM, NodeJS, PM2, and grunt
############################################

# NVM and prerequisites
apt-get install -y curl gnupg2
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
source ~/.bashrc

# Initial install of NodeJS (20.6.1 is an LTS version)
nvm install 20.6.1
npm install -g npm@latest

# Install node version manager, globally
mv ~/.nvm /opt/nvm
chmod -R 755 /opt/nvm
export NVM_DIR="/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/nvm:$PATH"

# Install last three NodeJS LTS versions
nvm install 16.20.2
nvm install 18.17.1
nvm alias default 20.6.1


# Install grunt, pm2 globally for all versions
nvm use v16
npm install -g grunt-cli
npm install -g pm2
nvm use v18
npm install -g grunt-cli
npm install -g pm2
nvm use v20
npm install -g grunt-cli
npm install -g pm2


############################################
# Install templates
############################################

rsync -r ./nginx/ /usr/local/hestia/data/templates/web/nginx/

############################################
# Update global bash.bashrc
############################################

if ! grep -Fxq "# begin hcpp-nodeapp" "/etc/bash.bashrc";then

cat <<EOT >> /etc/bash.bashrc
# begin hcpp-nodeapp
export NVM_DIR="/opt/nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/nvm:\$PATH"
# end hcpp-nodeapp
EOT

fi

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin NodeApp "<span style=\"font-size:large;color:green;\">&#11042;</span> NodeApp plugin has finished installing."