#!/bin/bash

# Update global bash.bashrc
sed '/^# begin hestiacp-nodeapp$/,/^# end hestiacp-nodeapp$/d' /etc/bash.bashrc > temp.txt && mv temp.txt /etc/bash.bashrc

############################################
# Uninstall templates
############################################
rm -f /usr/local/hestia/data/templates/web/nginx/NodeApp.sh
rm -f /usr/local/hestia/data/templates/web/nginx/NodeApp.tpl
rm -f /usr/local/hestia/data/templates/web/nginx/NodeApp.stpl
