#!/bin/bash

# Remove NodeJS, NVM, PM2, and grunt
rm -rf /opt/nvm

# Update global bash.bashrc
sed '/^# begin hcpp-nodeapp$/,/^# end hcpp-nodeapp$/d' /etc/bash.bashrc > temp.txt && mv temp.txt /etc/bash.bashrc

############################################
# Uninstall templates
############################################
rm -f /usr/local/hestia/data/templates/web/nginx/NodeApp.tpl
rm -f /usr/local/hestia/data/templates/web/nginx/NodeApp.stpl
